name: Cache Node and NPM Dependencies
description: Cache node modules and npm dependencies

inputs:
  node-version:
    description: 'Node.js version'
    required: false
    default: '20.x'
  working-dir: 
    description: 'Working directory'
    required: false
    default: '.'
  target-env:
    description: controls whether dev deps ate installed
    required: false
    default: dev

runs:
  using: composite
  steps:
    - name: steup node js version ${{inputs.node-version }} 
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}}}
    - name: cache dependencies
      id: cache
      uses: actions/cache@v3
      with:
        path: ${{ inputs.working-dir }}/node-modules
        key: node-modules-${{ hashFiles('${{ inputs.working-dir }}/package-lock.json')}}
    - name: install dependencies
      if: steps.cache.outputs.cache-hit != 'true' 
      run: npm ci
      shell: bash
      working-directory: ${{ inputs.working-dir }}

