name: 17.2 - custom actions js

on:
    workflow_dispatch:


jobs:
    dep-update:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: setup node dependencies
              uses: ./.github/actions/js-dependency-update
